# This workflow is triggered on pushes to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository's code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use the stable channel of Flutter

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze # Check for any analysis issues

      # Authenticate to Google Cloud so we can use Firebase tools
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      # Build the Flutter web application
      - name: Build Flutter web app
        run: flutter build web

      # Deploy the web app to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live # Deploy to the 'live' channel
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }} # You will need to add your Firebase Project ID as a secret
